version: 0.2
phases:
    install:
        commands:
            - yum update -y
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            #- $(aws ecr-public get-login --no-include-email --region $AWS_DEFAULT_REGION)
            #- aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z4e8w4e0
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...          

            - docker build . -t $IMAGE_REPO_NAME:$IMAGE_TAG
            #public.ecr.aws/z4e8w4e0/multi-arch-test
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/z4e8w4e0/$IMAGE_REPO_NAME:$IMAGE_TAG      
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push public.ecr.aws/z4e8w4e0/$IMAGE_REPO_NAME:$IMAGE_TAG
